/**
 * Project-level agent identity, override and learning layer.
 *
 * Every built-in roster agent has a base definition (role + prompt + tools +
 * skills) in the catalog. On top of that, **each project** can:
 *
 * 1. Override prompt, tools, skills, budget per role
 * 2. Accumulate learned wisdom specific to this codebase
 * 3. Attach a project-custom identity (name, avatar, tone)
 *
 * Resolution cascade (most → least specific):
 *   activeLearning.json  →  project-identity.md  →  catalog base
 *
 * Files live under `.wrongstack/agents/<role>/`:
 *   config.json   — static overrides (tools, budget, skillNames)
 *   identity.md   — custom prompt appendix (tone, project-specific rules)
 *   learned.md    — auto-generated wisdom from past sessions
 *   knowledge.md  — current-needs checklist (what versions to verify today)
 */

import { readFileSync, writeFileSync, rmSync, existsSync, mkdirSync, readdirSync } from 'node:fs';
import * as path from 'node:path';
import type { SubagentConfig } from '../../types/multi-agent.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ProjectAgentConfig {
  /**
   * Static tool allowlist override. When set, replaces the catalog tools
   * entirely (not merged). Omit to keep catalog defaults.
   */
  tools?: string[] | undefined;
  /** Static skill name override. Replaces catalog skillNames entirely. */
  skillNames?: string[] | undefined;
  /**
   * Budget overrides. Each field individually overrides the catalog budget.
   */
  budget?: {
    timeoutMs?: number | undefined;
    idleTimeoutMs?: number | undefined;
    maxIterations?: number | undefined;
    maxToolCalls?: number | undefined;
    maxTokens?: number | undefined;
    maxCostUsd?: number | undefined;
  } | undefined;
  /** Provider/model override for this role within the project. */
  provider?: string | undefined;
  model?: string | undefined;
  /**
   * Allowed capability overrides. Replaces catalog capabilities entirely.
   */
  allowedCapabilities?: readonly string[] | undefined;
}

/**
 * Current-knowledge manifest for a role: what live facts the agent should
 * fetch on every spawn to avoid hallucinating stale versions.
 */
export interface RoleKnowledgeManifest {
  role: string;
  /** Registry endpoints to query at spawn time, keyed by topic. */
  liveQueries: Record<string, { registry: string; key: string; description: string }>;
  /**
   * Human-readable checklist: "before answering questions about X, verify Y
   * from the live registry". Injected verbatim into the subagent prompt.
   */
  checklist: string[];
  /**
   * Minimum confidence threshold before the role should re-verify a live
   * source rather than relying on its own training data (0.0–1.0). Default 0.5.
   */
  verifyThreshold: number;
}

// ---------------------------------------------------------------------------
// Path helpers
// ---------------------------------------------------------------------------

function agentsDir(projectRoot?: string): string {
  const root = projectRoot ?? process.cwd();
  return path.join(root, '.wrongstack', 'agents');
}

function roleDir(role: string, projectRoot?: string): string {
  return path.join(agentsDir(projectRoot), role);
}

// ---------------------------------------------------------------------------
// Project agent config loading
// ---------------------------------------------------------------------------

/**
 * Load the project-level agent config for a given role.
 * Returns `undefined` when no project override exists.
 */
export function loadProjectAgentConfig(
  role: string,
  projectRoot?: string,
): ProjectAgentConfig | undefined {
  const cfgPath = path.join(roleDir(role, projectRoot), 'config.json');
  try {
    const raw = readFileSync(cfgPath, 'utf8');
    return JSON.parse(raw) as ProjectAgentConfig;
  } catch {
    return undefined;
  }
}

/**
 * Load the project-level identity appendix for a given role.
 * Appended to the subagent prompt after the base role prompt and policy.
 * Returns the empty string when no identity file exists.
 */
export function loadProjectAgentIdentity(
  role: string,
  projectRoot?: string,
): string {
  const identityPath = path.join(roleDir(role, projectRoot), 'identity.md');
  try {
    return readFileSync(identityPath, 'utf8').trim();
  } catch {
    return '';
  }
}

/**
 * Load the learning-derived wisdom for a given role.
 * Appended to the subagent prompt as a "knowledge from past sessions" block.
 * The learning file is auto-generated by the `memory-curator` or
 * `self-improving` agent roles and contains de-duplicated, curated findings.
 */
export function loadProjectAgentLearned(
  role: string,
  projectRoot?: string,
): string {
  const learnedPath = path.join(roleDir(role, projectRoot), 'learned.md');
  try {
    return readFileSync(learnedPath, 'utf8').trim();
  } catch {
    return '';
  }
}

/**
 * Load the current-knowledge checklist for a given role.
 * Returns the built-in directive if no project override exists.
 * The checklist guides the agent on what to verify from live registries
 * before answering questions in its domain.
 */
export function loadRoleKnowledgeManifest(
  role: string,
  projectRoot?: string,
): RoleKnowledgeManifest | undefined {
  // First look for project-level knowledge manifest
  const projectPath = path.join(roleDir(role, projectRoot), 'knowledge.json');
  try {
    const raw = readFileSync(projectPath, 'utf8');
    return JSON.parse(raw) as RoleKnowledgeManifest;
  } catch {
    // Fall back to built-in manifests
    return BUILT_IN_KNOWLEDGE_MANIFESTS[role];
  }
}

/**
 * Merge a project agent config onto a base `SubagentConfig`.
 * Returns a new config; does not mutate either input.
 */
export function applyProjectAgentConfig(
  base: SubagentConfig,
  projectConfig: ProjectAgentConfig | undefined,
): SubagentConfig {
  if (!projectConfig) return base;
  const result: SubagentConfig = { ...base };
  if (projectConfig.tools !== undefined) result.tools = [...projectConfig.tools];
  if (projectConfig.skillNames !== undefined) result.skillNames = [...projectConfig.skillNames];
  if (projectConfig.provider !== undefined) result.provider = projectConfig.provider;
  if (projectConfig.model !== undefined) result.model = projectConfig.model;
  if (projectConfig.allowedCapabilities !== undefined) {
    result.allowedCapabilities = [...projectConfig.allowedCapabilities];
  }
  if (projectConfig.budget) {
    if (projectConfig.budget.timeoutMs !== undefined) result.timeoutMs = projectConfig.budget.timeoutMs;
    if (projectConfig.budget.idleTimeoutMs !== undefined) result.idleTimeoutMs = projectConfig.budget.idleTimeoutMs;
    if (projectConfig.budget.maxIterations !== undefined) result.maxIterations = projectConfig.budget.maxIterations;
    if (projectConfig.budget.maxToolCalls !== undefined) result.maxToolCalls = projectConfig.budget.maxToolCalls;
    if (projectConfig.budget.maxTokens !== undefined) result.maxTokens = projectConfig.budget.maxTokens;
    if (projectConfig.budget.maxCostUsd !== undefined) result.maxCostUsd = projectConfig.budget.maxCostUsd;
  }
  return result;
}

/**
 * Build the full project-contextualized prompt for a given role.
 *
 * Cascade, from start to end:
 *   1. Base role prompt from instruction files (agentPrompt(id))
 *   2. Technology policy (appended by agentPrompt)
 *   3. Project identity appendix (identity.md)
 *   4. Learned wisdom (learned.md)
 *   5. Live-knowledge checklist
 */
// ---------------------------------------------------------------------------
// Update / reset / improve API
// ---------------------------------------------------------------------------

/**
 * Write or update the learned wisdom file for a given role.
 * Appends to existing content when `mode` is 'append'; replaces when
 * it is 'replace'. Returns the full path written so callers can log it.
 */
export function updateProjectAgentLearned(
  role: string,
  content: string,
  projectRoot?: string,
  mode: 'append' | 'replace' = 'append',
): string {
  const dir = roleDir(role, projectRoot);
  mkdirSync(dir, { recursive: true });
  const path_ = path.join(dir, 'learned.md');
  const existing = (() => {
    try {
      return readFileSync(path_, 'utf8');
    } catch {
      return '';
    }
  })();
  const newContent =
    mode === 'append' && existing
      ? `${existing}\n${content}`
      : content;
  writeFileSync(path_, newContent, 'utf8');
  return path_;
}

/**
 * Write or update the project identity file for a given role.
 * Replaces any existing identity.md with the new content.
 */
export function updateProjectAgentIdentity(
  role: string,
  content: string,
  projectRoot?: string,
): string {
  const dir = roleDir(role, projectRoot);
  mkdirSync(dir, { recursive: true });
  const path_ = path.join(dir, 'identity.md');
  writeFileSync(path_, content, 'utf8');
  return path_;
}

/**
 * Write or update the config.json override for a given role.
 */
export function updateProjectAgentConfig(
  role: string,
  config: ProjectAgentConfig,
  projectRoot?: string,
): string {
  const dir = roleDir(role, projectRoot);
  mkdirSync(dir, { recursive: true });
  const path_ = path.join(dir, 'config.json');
  writeFileSync(path_, JSON.stringify(config, null, 2), 'utf8');
  return path_;
}

/**
 * Write or update the knowledge manifest for a given role.
 */
export function updateProjectAgentKnowledge(
  role: string,
  manifest: RoleKnowledgeManifest,
  projectRoot?: string,
): string {
  const dir = roleDir(role, projectRoot);
  mkdirSync(dir, { recursive: true });
  const path_ = path.join(dir, 'knowledge.json');
  writeFileSync(path_, JSON.stringify(manifest, null, 2), 'utf8');
  return path_;
}

/**
 * Reset all project-level customizations for a given role back to factory
 * defaults by removing its `.wrongstack/agents/<role>/` directory.
 * When `role` is omitted or `'*'`, resets all roles.
 * Returns a list of paths that were removed.
 */
export function resetProjectAgentIdentity(
  role?: string,
  projectRoot?: string,
): string[] {
  const removed: string[] = [];
  if (!role || role === '*') {
    // Remove the entire agents directory
    const dir = agentsDir(projectRoot);
    if (existsSync(dir)) {
      rmSync(dir, { recursive: true, force: true });
      removed.push(dir);
    }
    return removed;
  }
  const dir = roleDir(role, projectRoot);
  if (existsSync(dir)) {
    rmSync(dir, { recursive: true, force: true });
    removed.push(dir);
  }
  return removed;
}

/**
 * Improve (or refresh) the project-custom identity for a given role
 * by clearing the learned.md and identity.md and re-scaffolding empty
 * templates. This is the explicit "refresh" trigger a user can call
 * when they want the project agent to re-learn from scratch.
 *
 * Returns a status report string.
 */
export function refreshProjectAgentIdentity(
  role: string,
  projectRoot?: string,
): string {
  const dir = roleDir(role, projectRoot);
  mkdirSync(dir, { recursive: true });

  // Remove learned wisdom and identity, keep config.json and knowledge.json
  for (const file of ['learned.md', 'identity.md']) {
    const fp = path.join(dir, file);
    try {
      rmSync(fp, { force: true });
    } catch {
      // file didn't exist
    }
  }

  // Re-scaffold identifying headers so the role knows these are available
  writeFileSync(path.join(dir, 'learned.md'), `# Learned wisdom for ${role}\n\n<!-- Accumulated project-specific knowledge appears here after agent-improve runs. -->\n`, 'utf8');
  writeFileSync(path.join(dir, 'identity.md'), `# Project identity for ${role}\n\n<!-- Describe how this agent should behave in the context of this project. -->\n`, 'utf8');

  return `Project identity for role "${role}" has been refreshed. The identity.md and learned.md files are reset to empty templates. Run an agent-improve pass to populate them with project-specific knowledge.`;
}

export function buildProjectContextualizedPrompt(
  basePrompt: string,
  role: string,
  projectRoot?: string,
): string {
  const parts: string[] = [basePrompt];

  const identity = loadProjectAgentIdentity(role, projectRoot);
  if (identity) {
    parts.push(`\n\n# Project custom identity\n\n${identity}`);
  }

  const learned = loadProjectAgentLearned(role, projectRoot);
  if (learned) {
    // Only include learned wisdom that has meaningful content (strip HTML comments)
    const meaningful = learned.replace(/<!--[\s\S]*?-->/g, '').trim();
    if (meaningful.length > 0) {
      parts.push(`\n\n# Learned wisdom for this project\n\n${learned}`);
    }
  }

  // Skip project identity when WRONGSTACK_AGENT_INSTRUCTIONS_DIR is set
  // (this is a test/override context — keep byte-exact equality with on-disk files).
  if (process.env['WRONGSTACK_AGENT_INSTRUCTIONS_DIR']) return parts.join('\n\n');

  // ── Capture mechanism: tell every agent HOW to persist new knowledge ──
  const effectiveProjectRoot = projectRoot || process.cwd();
  const learnedFilePath = path.join(effectiveProjectRoot, '.wrongstack', 'agents', role, 'learned.md');
  parts.push(`\n\n## Knowledge capture\n\nWhen you discover a project-specific pattern, convention, or decision that future "${role}" invocations should remember, end your response with a \`## LEARNED\` block. The runtime persists that content to:\n\n  \`\`\`\n  ${learnedFilePath}\n  \`\`\`\n\nCapture only durable, cross-session knowledge — never ephemeral task details.`);

  const knowledge = loadRoleKnowledgeManifest(role, projectRoot);
  if (knowledge && knowledge.checklist.length > 0) {
    const checklist = knowledge.checklist.map((item) => `- ${item}`).join('\n');
    parts.push(`\n\n## Current knowledge requirements\n\nVerify these before answering:\n${checklist}`);
  }

  return parts.join('\n\n');
}

// ---------------------------------------------------------------------------
// Learned-wisdom capture from agent output
// ---------------------------------------------------------------------------

// ─── learned.md automation contract ────────────────────────────────────────
//
//  TRIGGER  Primary: end of a delegated subagent task (delegate-tool.ts result
//           handler). The director's task resolution checks the final output
//           text for ## LEARNED blocks and calls captureLearnedFromAgentOutput.
//           Secondary: leader's own output after a user-invoked improvement
//           prompt ("improve the executor agent"). Never on intermediate tool
//           calls or every iteration — only once per task resolution.
//           Manual: `/agent-improve <role> capture` at any time.
//
//  GUARDRAILS
//
//  1. COOLDOWN  Per-role: minimum 120 seconds between captures. Tracks the
//     last capture timestamp in a module-level Map.  A capture within the
//     cooldown window is silently skipped (counter not bumped).
//
//  2. FREQUENCY CAP  Per-session: at most 3 captures per role before the
//     capture falls through to `/agent-improve` (human-gated). The session
//     is reset on process restart (module reload).
//
//  3. HUMAN-APPROVAL THRESHOLD  When `learned.md` exceeds `LEARNED_SOFT_LIMIT`
//     (8 KB) the next capture is deferred — the agent is asked to run
//     `/agent-improve <role> refresh` or the user must call it explicitly.
//     The hintLearnedNeedsSummarization() check is exposed so the CLI can
//     surface this in /agent-improve output.
//
//  4. SIZE  SOFT_LIMIT = 8 192 B → hintLearnedNeedsSummarization() returns true.
//           HARD_LIMIT = 16 384 B → `pruneToSize()` drops oldest entries.
//
//  5. CONTENT QUALITY  A block is skipped when:
//     - meaningful body (strip markdown) < 50 chars
//     - >70% of lines are code fences
//     - near-duplicate by Jaccard ≥ 0.55
//
//  OWNER  logic : packages/core/src/coordination/agents/project-agent-identity.ts
//         hooks : packages/core/src/coordination/delegate-tool.ts
//                 packages/cli/src/fleet/host.ts
// ---------------------------------------------------------------------------

export const LEARNED_SOFT_LIMIT = 8_192;
export const LEARNED_HARD_LIMIT = 16_384;

/**
 * Normalize text for dedup comparison: lowercase, strip punctuation, sort tokens.
 */
function normalizeForComparison(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .split(/\s+/)
    .sort()
    .join(' ');
}

// ─── Automation guardrails ───────────────────────────────────────────────────

const captureCooldowns = new Map<string, number>();   // role → timestamp
const captureFrequency  = new Map<string, number>();   // role → count

export const CAPTURE_COOLDOWN_MS = 120_000;   // 2 minutes
export const CAPTURE_MAX_PER_SESSION = 3;

/**
 * Check whether a new capture is allowed for this role. Returns a rejection
 * reason string when blocked, or undefined when capture may proceed.
 */
export function canCaptureNewLearned(
  role: string,
  existingSize: number,
  isManual: boolean,
): string | undefined {
  // Cooldown gate (bypassed for manual captures)
  if (!isManual) {
    const last = captureCooldowns.get(role);
    if (last && Date.now() - last < CAPTURE_COOLDOWN_MS) {
      return `Cooldown active for role "${role}" (${Math.ceil((CAPTURE_COOLDOWN_MS - (Date.now() - last)) / 1000)}s remaining)`;
    }
  }

  // Frequency cap (bypassed for manual captures)
  if (!isManual) {
    const count = captureFrequency.get(role) ?? 0;
    if (count >= CAPTURE_MAX_PER_SESSION) {
      return `Frequency cap reached for role "${role}" (${count}/${CAPTURE_MAX_PER_SESSION}). Use /agent-improve ${role} capture for manual override.`;
    }
  }

  // Size gate: when over SOFT_LIMIT, require manual approval
  if (existingSize > LEARNED_SOFT_LIMIT && !isManual) {
    return `learned.md for role "${role}" exceeds soft limit (${existingSize}B / ${LEARNED_SOFT_LIMIT}B). Run /agent-improve ${role} capture manually or /agent-improve ${role} refresh to reset.`;
  }

  return undefined;
}

/**
 * Per-role learning stats for monitoring UIs.
 */
export interface ProjectAgentLearnStats {
  role: string;
  exists: boolean;
  entryCount: number;
  totalBytes: number;
  lastCapture: string | null;
  lastCaptureTimestamp: number | null;
  cooldownRemainingMs: number;
  sessionCaptureCount: number;
  needsSummarization: boolean;
  learnedPath: string | null;
  identityPath: string | null;
  hasIdentity: boolean;
  hasConfig: boolean;
  hasKnowledge: boolean;
}

export function getProjectAgentLearnStats(
  role: string,
  projectRoot?: string,
): ProjectAgentLearnStats {
  const dir = roleDir(role, projectRoot);
  const learnedPath_ = path.join(dir, 'learned.md');
  const identityPath_ = path.join(dir, 'identity.md');
  const configPath_ = path.join(dir, 'config.json');
  const knowledgePath_ = path.join(dir, 'knowledge.json');
  let learnedText = '';
  try { learnedText = readFileSync(learnedPath_, 'utf8'); } catch { /* no file */ }
  const exists = learnedText.length > 0;
  const entries = exists ? learnedText.split('\n---\n') : [];
  const entryCount = exists ? entries.length : 0;
  const lastTs = captureCooldowns.get(role) ?? null;
  const cooldownRemaining = lastTs ? Math.max(0, CAPTURE_COOLDOWN_MS - (Date.now() - lastTs)) : 0;
  const freq = captureFrequency.get(role) ?? 0;

  return {
    role,
    exists,
    entryCount,
    totalBytes: learnedText.length,
    lastCapture: lastTs ? new Date(lastTs).toISOString() : null,
    lastCaptureTimestamp: lastTs,
    cooldownRemainingMs: cooldownRemaining,
    sessionCaptureCount: freq,
    needsSummarization: exists ? hintLearnedNeedsSummarization(role, projectRoot).length > 0 : false,
    learnedPath: exists ? learnedPath_ : null,
    identityPath: existsSync(identityPath_) ? identityPath_ : null,
    hasIdentity: existsSync(identityPath_),
    hasConfig: existsSync(configPath_),
    hasKnowledge: existsSync(knowledgePath_),
  };
}

/**
 * List every role that has a learned.md or identity.md.
 */
export function listProjectAgentRoles(projectRoot?: string): string[] {
  const dir = agentsDir(projectRoot);
  try {
    return (readdirSync as (dir: string) => string[])(dir).filter((name: string) => {
      const sub = path.join(dir, name);
      try { return existsSync(path.join(sub, 'learned.md')) || existsSync(path.join(sub, 'identity.md')); } catch { return false; }
    });
  } catch { return []; }
}

/**
 * Re-export existsSync so callers can check file existence without importing fs.
 */
export { existsSync };

/**
 * Detect semantic conflicts between different roles' learned wisdom.
 * Returns entries where token overlap ≥ 0.60, which suggests the two
 * roles have learned about the same topic — potentially contradicting.
 */
export function detectLearnedConflicts(projectRoot?: string): Array<{
  roleA: string;
  roleB: string;
  snippetA: string;
  snippetB: string;
  similarity: number;
  detectedAt: string;
}> {
  const roles = listProjectAgentRoles(projectRoot);
  const entries: { role: string; normalized: string; raw: string }[] = [];
  for (const role of roles) {
    const text = loadProjectAgentLearned(role, projectRoot);
    if (!text || text.trim().length < 50) continue;
    entries.push({ role, normalized: normalizeForComparison(text), raw: text });
  }
  const conflicts: Array<{
    roleA: string; roleB: string; snippetA: string; snippetB: string;
    similarity: number; detectedAt: string;
  }> = [];
  for (let i = 0; i < entries.length; i++) {
    const a = entries[i]!;
    for (let j = i + 1; j < entries.length; j++) {
      const b = entries[j]!;
      const sim = tokenOverlap(a.normalized, b.normalized);
      if (sim >= 0.60) {
        conflicts.push({
          roleA: a.role, roleB: b.role,
          snippetA: a.raw.slice(0, 200), snippetB: b.raw.slice(0, 200),
          similarity: sim, detectedAt: new Date().toISOString(),
        });
      }
    }
  }
  return conflicts.sort((a, b) => b.similarity - a.similarity);
}

/**
 * Return the Jaccard similarity (0–1) of two normalised token sets.
 */
function tokenOverlap(a: string, b: string): number {
  const setA = new Set(a.split(/\s+/));
  const setB = new Set(b.split(/\s+/));
  const intersect = new Set([...setA].filter((t) => setB.has(t)));
  const union = new Set([...setA, ...setB]);
  return union.size === 0 ? 0 : intersect.size / union.size;
}

/**
 * Split an existing learned.md body into individual entries.
 * Entries are delimited by `---\n\n` sequences.
 */
function splitLearnedEntries(body: string): string[] {
  return body
    .split(/\n---\n+/)
    .map((entry) => entry.trim())
    .filter(Boolean);
}

/**
 * Remove entries from the learned body until it fits within `targetBytes`,
 * dropping the *oldest* entries first (entries are in chronological order
 * since new items are appended at the end).
 */
function pruneToSize(body: string, targetBytes: number): string {
  const entries = splitLearnedEntries(body);
  const result: string[] = [];
  let size = 0;
  // Iterate from newest (last) to oldest (first)
  for (let i = entries.length - 1; i >= 0; i--) {
    const current = entries[i]!;
    const entry = `\n\n---\n\n${current}`;
    if (size + entry.length <= targetBytes) {
      result.unshift(current);
      size += entry.length;
    }
  }
  return result.join('\n\n---\n\n');
}

/**
 * Learned-wisdom capture from agent output.
 *
 * Scans `output` for `## LEARNED` blocks and persists each unique,
 * quality-passing block to the role's `learned.md`.  Deduplication is
 * performed against the existing content; if the new block is a near-
 * duplicate (token overlap ≥ 0.55) it is silently skipped.
 *
 * When the resulting file would exceed `LEARNED_HARD_LIMIT` (16 KB)
 * the oldest entries are rotated out before writing.
 *
 * @returns the number of **new** items actually persisted (0 if none).
 */
export function captureLearnedFromAgentOutput(
  output: string,
  role: string,
  projectRoot?: string,
  isManual = false,
): number {
  if (!output) return 0;

  // Read existing learned.md once
  const existingRaw = loadProjectAgentLearned(role, projectRoot) ?? '';

  // Guardrails: cooldown, frequency cap, and size gate
  const guard = canCaptureNewLearned(role, existingRaw.length, isManual);
  if (guard) return 0;

  // Track cooldown and frequency (even when isManual — resets the clock)
  captureCooldowns.set(role, Date.now());
  captureFrequency.set(role, (captureFrequency.get(role) ?? 0) + 1);

  const regex = /^##\s*LEARNED\s*$/gim;
  let startMatch: RegExpExecArray | null;
  let count = 0;
  const existingBody = existingRaw.replace(/^> Captured .+$/gm, '').trim();
  const existingNormalized = existingBody ? normalizeForComparison(existingBody) : '';

  // Collect candidate blocks
  const candidates: string[] = [];
  while ((startMatch = regex.exec(output)) !== null) {
    const blockStart = startMatch.index + startMatch[0].length;
    const rest = output.slice(blockStart);
    const nextHeading = /^##\s/gm.exec(rest);
    const blockEnd = nextHeading ? blockStart + nextHeading.index : output.length;
    const content = output.slice(blockStart, blockEnd).trim();
    candidates.push(content);
    regex.lastIndex = Math.max(regex.lastIndex, blockEnd);
  }

  if (candidates.length === 0) return 0;

  let newContent = existingRaw;

  for (const content of candidates) {
    // ── Quality gate 1: minimum length ──────────────────────────────────
    const meaningful = content.replace(/```[\s\S]*?```/g, '').trim();
    if (meaningful.length < 50) continue;

    // ── Quality gate 2: code-only heuristic ─────────────────────────────
    const codeLines = (content.match(/^```/gm) ?? []).length;
    const totalLines = content.split('\n').length;
    if (totalLines > 5 && codeLines / totalLines > 0.7) continue;

    // ── Dedup gate: token overlap with existing content ─────────────────
    const candidateNorm = normalizeForComparison(content);
    if (existingNormalized && tokenOverlap(candidateNorm, existingNormalized) >= 0.55) continue;

    // ── Persist with timestamp ──────────────────────────────────────────
    const stamped = `> Captured ${new Date().toISOString().slice(0, 10)}\n\n${content}`;
    newContent = newContent
      ? `${newContent}\n\n---\n\n${stamped}`
      : stamped;
    count++;
  }

  if (count === 0) return 0;

  // ── Size enforcement: rotate oldest entries when over HARD_LIMIT ─────
  if (newContent.length >= LEARNED_HARD_LIMIT) {
    newContent = pruneToSize(newContent, LEARNED_SOFT_LIMIT);
  }

  // ── Persist: ensure directory exists, then write ─────────────────────
  mkdirSync(roleDir(role, projectRoot), { recursive: true });
  writeFileSync(
    path.join(roleDir(role, projectRoot), 'learned.md'),
    newContent,
    'utf8',
  );
  return count;
}

/**
 * Signal the host that a background summarisation pass is warranted.
 * Called by `captureLearnedFromAgentOutput` when the **new** learned size
 * crosses `LEARNED_SOFT_LIMIT`.  The host is responsible for scheduling a
 * low-priority consolidation task (typically via the Brain or a shadow agent).
 *
 * The summary _mechanism_ is intentionally shallow here — the real
 * summarisation is an LLM call that should run as a deferred, uncritical
 * fleet task so it never blocks a user-facing operation.
 *
 * @returns a summary brief for the host, or '' when no action is needed.
 */
export function hintLearnedNeedsSummarization(role: string, projectRoot?: string): string {
  const learned = loadProjectAgentLearned(role, projectRoot);
  if (!learned) return '';
  if (learned.length < LEARNED_SOFT_LIMIT) return '';
  return `Learned wisdom for role "${role}" is ${learned.length} B (soft limit ${LEARNED_SOFT_LIMIT}). Schedule a low-priority consolidation pass.`;
}

// ---------------------------------------------------------------------------
// Built-in knowledge manifests (per role type, current-needs checklist)
// ---------------------------------------------------------------------------

const BUILT_IN_KNOWLEDGE_MANIFESTS: Record<string, RoleKnowledgeManifest> = {
  'android': {
    role: 'android',
    liveQueries: {
      agp: { registry: 'https://developer.android.com/build/releases/gradle-plugin', key: 'latest', description: 'Android Gradle Plugin latest stable' },
      kotlin: { registry: 'https://registry.npmjs.org/kotlin/latest', key: 'version', description: 'Kotlin latest stable' },
      compileSdk: { registry: 'https://developer.android.com/about/versions', key: 'api_level', description: 'Current stable API level' },
    },
    checklist: [
      'Current Android Gradle Plugin version (8.x+)',
      'Current Kotlin version (2.x+)',
      'Current compileSdk / targetSdk (≥ 34, check Play Store policy)',
      'Current Jetpack Compose stable version',
      'All third-party dependencies are at latest compatible minor',
    ],
    verifyThreshold: 0.5,
  },
  'frontend': {
    role: 'frontend',
    liveQueries: {
      react: { registry: 'https://registry.npmjs.org/react/latest', key: 'version', description: 'React latest stable' },
      nextjs: { registry: 'https://registry.npmjs.org/next/latest', key: 'version', description: 'Next.js latest stable' },
    },
    checklist: [
      'Current React version (pinned in package.json)',
      'Current Next.js / Vite / framework version',
      'Node.js runtime version (project .nvmrc or engines)',
      'All devDependencies are at latest compatible versions',
      'Browser compatibility targets from browserslist',
    ],
    verifyThreshold: 0.5,
  },
  'executor': {
    role: 'executor',
    liveQueries: {
      node: { registry: 'https://registry.npmjs.org/node/latest', key: 'version', description: 'Node.js latest LTS' },
    },
    checklist: [
      'Node.js version from .nvmrc or package.engines',
      'TypeScript version from package.json',
      'Package manager (pnpm ≥ 9) from packageManager',
      'Current toolchain: esbuild, vitest, etc.',
    ],
    verifyThreshold: 0.6,
  },
};
